name: Sync issue to private repositories

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

permissions:
  contents: read
  issues: read

jobs:
  sync-ios-issue:
    uses: HYRMedia-LLC/shared-public-workflows/.github/workflows/sync-public-issue-to-private.yml@main
    with:
      target_repository: HYRMedia-LLC/whats-the-hundo
      route_label: iOS
    secrets:
      issue_sync_token: ${{ secrets.ISSUE_SYNC_TOKEN }}

  sync-android-issue:
    uses: HYRMedia-LLC/shared-public-workflows/.github/workflows/sync-public-issue-to-private.yml@main
    with:
      target_repository: HYRMedia-LLC/whats-the-hundo-android
      route_label: Android
    secrets:
      issue_sync_token: ${{ secrets.ISSUE_SYNC_TOKEN }}
